### ISSUE TITLE
Make tokenizer operate on raw bytes

### ISSUE THREAD

**Issue by Ygg01** [untitaker/html5gum#12]
When I and SimonSapin were looking into html5ever speed up, one low-hanging fruit left was iterating over bytes rather than on Characters. It seems iterating on chars does a lot of UTF8 bounds check. 

With bytes iteration and memchr, you might get a few speed-ups.

**Comment by untitaker** [comment]
I probably want to get away from str in the mid term, yes. Still need to figure out if it's still going to be a literal character stream in the statemachine then though

**Comment by untitaker** [comment]
I believe it may be that html5gum's entire design is too naive to get a significant boost from memchr. even if I redesign its entire interface to pattern-match on bytes, it will always look at individual characters without deeper changes. Because it's just a literal port of the statemachine found in the spec.

**Comment by Ygg01** [comment]
Even without memchr, the fact you're not revalidating `String` bounds check might be good enough.

Anyway here is my approximate [take on it](https://github.com/Ygg01/xml5). Just keep in mind it's very WIP. I haven't done extensive tests on it. Especially the memchr.

To keep in mind memchr has a limit of searching up to 3 different bytes which aren't enough for some states.  Although most `(space)` | `(tab)` | `(newline)` can be separated into a skip whitespace method on a reader , which I'm yet to do.

**Comment by untitaker** [comment]
thanks will check. btw you need `\r` and `\n` for `(newline)`, this is not visible in state transitions in html5gum, because it is currently normalized in `read_char`. Some investigation and measurements are needed to determine which type of whitespace makes most sense to be grouped into a memchr call, from a performance pov

**Comment by untitaker** [comment]
I _suspect_ memchr with _just_ `0x20` and `\t` would yield a bunch of improvements, since that tends to be the most common form of consecutive whitespace.

**Comment by untitaker** [comment]
#18 added memchr, which didn't yield significant perf gains unless the input had a ton of whitespace.

#25 changes everything to run on bytes, so far I haven't seen significant perf gains

feedback apprechiated, especially around validating input stream characters

**Comment by untitaker** [comment]
#25 is merged. 
there may be remaining low-hanging fruits wrt performance, but nothing obvious.

**Comment by Ygg01** [comment]
Seems good.
