### ISSUE TITLE
use arrayvec crate instead

### ISSUE THREAD

**Issue by lebensterben** [untitaker/html5gum#32]
Though the intention is to avoid using unsafe Rust, the current implementation of `html5gum::arrayvec::ArrayVec` needs much improvement and the there's no real unsafety if we just use the `arrayvec` crate.

---

Consider `html5gum::arrayvec::ArrayVec::push()`:
```rust
    pub fn push(&mut self, item: T) {
        self.content[self.len] = item;
        self.len += 1;
    }
```

Keep pushing and you are guaranteed to get an runtime index out of bound error.

While `arrayvec::ArrayVec::push()` checks the capacity and there's no unsafety or run-time error.
```rust
    fn push(&mut self, element: Self::Item) {
        self.try_push(element).unwrap()
    }

    fn try_push(&mut self, element: Self::Item) -> Result<(), CapacityError<Self::Item>> {
        if self.len() < Self::CAPACITY {
            unsafe {
                self.push_unchecked(element);
            }
            Ok(())
        } else {
            Err(CapacityError::new(element))
        }
    }
```

---

Consider `html5gum::arrayvec::ArrayVec::drain()`
```rust
    pub fn drain(&mut self) -> &[T] {
        let rv = &self.content[..self.len];
        self.len = 0;
        rv
    }
```

It doesn't drain anything actually. It just gives you a view of the `content`.

---

I propose to use `arrayvec::ArrayVec` instead. If you wish, we can use new type pattern and only expose `new()`, `push()`, and `drain()` function.

**Comment by untitaker** [comment]
>Keep pushing and you are guaranteed to get an runtime index out of bound error.

this is the api contract for arrayvec as well, it _will_ panic in `push()` by unwrapping the result of `try_push`

in this crate's impl, if `self.len` is one past the end of the array, the arrayvec is full, and the index operation will panic. this can be made more explicit, but then we may accidentally regress performance, and this is internal API so I didn't bother.

>It doesn't drain anything actually

it resets `len` to 0, so it's equivalent to `drain(..)` (ranged drain is not supported)

----

right now the README says html5gum has no mandatory dependencies. I added jetscii because it offers significant performance gains that can't be replicated in safe code, but even that one is optional, and I believe the barrier for new dependencies should be similarly high

that said the library is still WIP, and many features I want (like tree builder or css selectors) will probably bloat the deptree, unless they are optional

**Comment by untitaker** [comment]
@lebensterben i explained my dependency policy in a new CONTRIBUTING document in master in additional to the freaky test harness, does it make sense?

**Comment by lebensterben** [comment]
> this can be made more explicit, but then we may accidentally regress performance, and this is internal API so I didn't bother.

The current implementation, i.e. `html5gum::arrayvec::ArrayVec::push()`, though as an internal API, still may cause panic at runtime. This would become a larger issue if you expect other people contribute to this project and use this function.

Suppose a library user encountered a panic due to this, the panic behaviour on his platform could be just aborting the program and not trying to rewind anything. If he has some data types that requires manual memory management, for example it doesn't implements Drop, then at panic there might be some memory with sensitive data not cleared. (Normally OS would prevent illegal access of memory but attacker may dump the memory to get its contents).

So at very least, for **safety**, we should eliminate the possibility of a panic.

Surely performance is important, and I would suggest to make `html5gum::arrayvec::ArrayVec::push()` unsafe. But that's against your principle here...

**Comment by lebensterben** [comment]
As for `html5gum::arrayvec::ArrayVec::drain()`, at very least that's a bad naming.

In STD `drain()` returns an iterator and regardless of whether the iterator is consumed, the original data is removed.

Currently, `html5gum::arrayvec::ArrayVec::push()` doesn't return an iterator and the original data is not removed.

**Comment by lebensterben** [comment]
In the linked PR, I've used the newtype pattern and only exposed the API this library used.

Though `arraryvec` crate is unsafe, but at least the three functions doesn't have unsafe usages.

**Comment by untitaker** [comment]
`ArrayVec` is used instead of `Vec` precisely because we know the (static) upper bound of items the crate will push into the instance. If it pushes more than that, it is a logic bug in html5gum and must be fixed. It should not be possible regardless of how the crate's public API is used.

Please double-check your claims about `drain()` and `push()`. I am absolutely certain those methods work the same way as in the arrayvec crate, and your PR _does not_ change their behavior. If you disagree please provide a code sample that actually does behave differently between your PR and master.

**Comment by untitaker** [comment]
To challenge your claims directly:

>Currently, html5gum::arrayvec::ArrayVec::push() doesn't return an iterator and the original data is not removed.

It is true that `ArrayVec::drain()` (sic?) does not return an iterator (but a slice), but it _does_ correctly remove the old data by resetting `self.len = 0`. The effect is the same: `drain()` clears the array and returns the array's old items.

>though as an internal API, still may cause panic at runtime.

This is exactly the same behavior as `arrayvec::ArrayVec::push` on crates.io. If you don't want a panic, use `try_push`, but I believe that would be a mistake here.

**Comment by lebensterben** [comment]
> but it does correctly remove the old data by resetting self.len = 0

Setting the `len` field to zero makes it impossible inside Rust to access the data. But the memory is not cleared.

For `arrayvec::ArrayVec::drain()` or other `drain()` functions in STD.
- `drain()` works in the way that it returns a `Drain` struct which holds a pointer to the original data and an iterator to the part of data to be removed.
- `Drain` struct implements `Drop` trait in the way that it removes the data in the iterator, even if they are not used (i.e. the iterator is not consumed).
- Note that `Drain` is dropped **before** the original data type. That's how it *logically* guarantees that the part of data will be removed.
- That is to say, whenever you call `drain()`, it gives you the struct `Drain` which drops the data regardless of whether they're consumed.

For the current implementation of `drain`, see the playground example: https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=5a4a409ecd57ea191b65aee0a325ecfc

**Comment by lebensterben** [comment]
As for `arrayvec::ArrayVec::push`, I don't think we should use `try_push` for performance reason.

But we must note this in the documentation or comment about the potential panic and why we don't need to worry about it.
(Optionally, in debug build, we can `debug_assert` that the capacity is not exceeded.

**Comment by untitaker** [comment]
I'm going to close this issue because I find this conversation/debate extremely frustrating. Originally you were claiming that the vendored arrayvec has fundamentally different behavior from the crate (and therefore we need to start using the crate), which I disproved, then tell me that `drain()` needs to return a `Drain` object + "clear" items from memory to be considered equivalent. I think this is unnecessarily pedantic and completely besides the point of a vendored subset of arrayvec that is supposed to be simpler to audit by being 10 lines instead of 100-1000 lines of code.

Both std vec and arrayvec will in fact not clear any memory: they will leave the memory as-is and reset the len. The fact that this memory is not visible in their respective debug implementations is 1) needed in their case because it would be undefined behavior to interpret that memory as item and use its `Debug` impl 2) a fair criticism of the `Debug` implementation of the vendored arrayvec, but in any case besides the point with regard to the API or behavioral correctness. Also clearing memory or executing item's `Drop` impls does not matter with `Copy` items.

Fundamentally two things remain true:

* `drain()` "deletes" items in that they don't show up in successive `drain()` calls, but does not go through the effort of clearing them from memory. This is true across _all_ sorts of vectors. The difference I see right now is that ours has a auto-derived debug impl that shows the old data.
* `push()` panics if the bounds are exceeded, in both versions

...and that's all that matters.

Aside: I think it would be a good improvement to document why a potential panic cannot actually happen, but it would require documentation and linting effort to do so consistently across the codebase. in `reader.rs` you will find several potentially-panicking slice accesses that IMO are all not problematic, but for undocumented reasons.

**Comment by lebensterben** [comment]
> arrayvec will in fact not clear any memory: they will leave the memory as-is and reset the len.

That's incorrect.
It's dropped here
https://docs.rs/arrayvec/latest/src/arrayvec/arrayvec.rs.html#973

**Comment by untitaker** [comment]
I am talking about the memory of the array, not running destructors. I get that `Drop` needs to be executed, but all of our items are restricted to be `Copy` so it doesn't matter.

**Comment by untitaker** [comment]
Concretely, if you build a `Vec<u8>`, and drain it, there is basically nothing that needs to run besides the `set_len`. you can leave the items where they are and overwrite them on the next `push()`.

If you have a `Vec<String>`, you can do the same, but you need to go through each `String` struct, and deallocate the string data itself (for which you will find a pointer in the string struct). The string struct however still stays in the `Vec`, and as long as nobody accesses it or constructs a Rust reference to it, there is no memory unsafety.

In the case where all your items are `Copy` (like u8) you can do those sorts of shenanigans without unsafe Rust. Items that impl `Copy` _cannot_ have a custom `Drop`.
