### ISSUE TITLE
Document why jetscii is used instead of memchr

### ISSUE THREAD

**Issue by not-my-profile** [untitaker/html5gum#84]
I see that this was changed in d759695c07cb934fc605be67e4f4492a9dd4fba3 without any explanation in the commit message.

I think it would be nice to add a comment above the `jetscii` dependency in `Cargo.toml` that briefly comments on why it's used instead of `memchr`.

**Comment by untitaker** [comment]
Jetscii is able to deal with searching 16 needles in a haystack at once, and memchr can only do 3. We have some uses of fast_read_char that need 4 needles.

That said, a lot of the benchmarking I did around then turns out to be non-reproducible, for example, I recall that jetscii had significant performance boost over a stdlib `str.find`, but nowadays it is only marginally faster.

The place where this matters the most is the `data` benchmark, or wherever one has large amounts of contiguous text with no interleaved tokens (large comments too)

I don't exactly know what kind of comment I should write in Cargo.toml that would help here. IMO the ideal place to provide this justification would've been the commit message, but it's too late for that.

**Comment by untitaker** [comment]
addendum, i don't know if memchr is faster or slower than jetscii in the end, but the additional branching I did for dispatching certainly made it slower. I don't even know if it was ever viable in terms of performance.
